version: "2"

services:
  web:
    container_name: dockerdev
    build: ./
    ports:
      - "8000:8000"
    environment:
      DD_DB_HOST: mongo
      MONGO_URL: mongodb://root:example@mongo:27017
    depends_on:
      - mongo
  mongo:
    image: "mongo:6.0.2"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"